from .ai_generation import generate_lesson, generate_quiz
from .config import load_settings
from .guardrails import check_question
from .db import (
    admin_load_all,
    admin_lessons_filtered,
    admin_cost_by_day,
    admin_cost_by_provider,
    admin_device_split,
    admin_lessons_by_day,
    admin_lessons_by_hour,
    admin_overview,
    admin_perf_by_day,
    admin_recent_errors,
    admin_recent_lessons,
    admin_slowest_lessons,
    admin_top_questions,
    delete_cached_lesson,
    get_cached_lesson,
    get_lesson_from_calls,
    get_pool_stats,
    get_write_stats,
    init_db,
    ip_calls_last_hour,
    pin_cached_lesson,
    record_api_call,
    save_cached_lesson,
    save_feedback,
    today_spend_usd,
)
from .geo import extract_and_lookup
from .image_gen import generate_image
from .renderer import render as render_spec
from .tts import synthesize

__all__ = [
    "admin_load_all",
    "admin_lessons_filtered",
    "generate_lesson",
    "generate_quiz",
    "check_question",
    "load_settings",
    "init_db",
    "save_feedback",
    "record_api_call",
    "extract_and_lookup",
    "synthesize",
    "get_cached_lesson",
    "get_lesson_from_calls",
    "save_cached_lesson",
    "delete_cached_lesson",
    "pin_cached_lesson",
    "today_spend_usd",
    "ip_calls_last_hour",
    "render_spec",
    "generate_image",
    "admin_overview",
    "admin_lessons_by_day",
    "admin_lessons_by_hour",
    "admin_device_split",
    "admin_top_questions",
    "admin_cost_by_day",
    "admin_cost_by_provider",
    "admin_recent_lessons",
    "admin_perf_by_day",
    "admin_slowest_lessons",
    "admin_recent_errors",
]
